name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the behavior.
      placeholder: |
        1. Create client with '...'
        2. Call method '...'
        3. Observe error '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or stack traces.
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      placeholder: "0.2.0"
    validations:
      required: true
  - type: input
    id: lang-version
    attributes:
      label: Node.js Version
      placeholder: "e.g., 22.x"
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: Streamline Server Version
      placeholder: "0.2.0"
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., Ubuntu 22.04, macOS 14.0, Windows 11"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, logs, or configuration.
